### ISSUE TITLE
Special characters are encoded

### ISSUE THREAD

**Issue by ot-dev** [boneskull/angular-tags#20]
Apostraphes, quotes, etc, show up fine in the typeahead list, but show up encoded in the pillbox. This prevents most code from working properly during the removed event because the tag name is encoded and won't match model data.

**Comment by atruskie** [comment]
FYI, I've had this problem too. I think the original repo has patched this... see https://github.com/boneskull/angular-tags/commit/c59cb657d1a3898687918ef6eb342366232601b1
