### ISSUE TITLE
Does not work in IE8

### ISSUE THREAD

**Issue by crisbeto** [boneskull/angular-tags#27]
Tested on a clean Windows XP SP3 with IE8 and doesn't work at all, I'm guessing it's because it uses the custom <tags> element.

**Comment by boneskull** [comment]
I expected as much.  Have you tried [IE Shiv](https://github.com/angular-ui/ui-utils/tree/master/modules/ie-shiv)?

AngularJS is dropping IE8 support, and the application that we produced that prompted this project does not support IE8 either, so there aren't really plans to do anything about this.

Thank you
