### ISSUE TITLE
Nullifies rest of model

### ISSUE THREAD

**Issue by kliolios** [boneskull/angular-tags#37]
I am using angular-tags in parallel with angular-xeditable form in a modal for an array that is part of an object ("asset.keywords").  When I add tags it saves the updated version of keywords but erases all the other member data of "asset".  (for example "asset.name") Does this sound familiar?  Any idea why?

Thanks and gr8 job
Dino

**Comment by boneskull** [comment]
yikes. will look into it. could you provide example code?

**Comment by kliolios** [comment]
Doh,

Totally unrelated.  Just bad timing.  Sorry about that.  Close or even delete the ticket.

Once again awesome job.
Dino
