### ISSUE TITLE
Typeahead values not coming properly.

### ISSUE THREAD

**Issue by false9striker** [boneskull/angular-tags#40]
Please see the image. 
![image](https://cloud.githubusercontent.com/assets/628338/3084858/71921c96-e501-11e3-9054-9001077a9f93.png)

Values are getting displayed like this, but when i select something it fills the input box with proper value. Please help.

**Comment by boneskull** [comment]
@false9striker angular-tags is incompatible with newer versions of AngularJS.  I'm working on upgrading.  You can keep an eye on [this branch](https://github.com/boneskull/angular-tags/tree/v1.0.0) in the meantime, but it doesn't work yet.

**Comment by false9striker** [comment]
Please tell how long i need to wait to get a fix for this? If i move back to v1.2.0-rc.2 it works fine, but i can't do that because of some other dependencies.

**Comment by false9striker** [comment]
Could you please give a quick fix  for this issue otherwise? With latest angular only the typeahead has issues while listing contents as i mentioned above. Everything else works great. Good job!

**Comment by boneskull** [comment]
No quick fix is forthcoming.  I have yet to diagnose the issue; still
trying to determine which version of AngularJS the problem starts with.  I
hope to have v1.0.0 released "soon" but until then PRs are welcome.

**Comment by false9striker** [comment]
Thanks for the reply. :+1: 

I got it working without doing anything. Only change i did was i included angular-strap.min.js & angular-strap.tpl.min.js for one other functionality.
