### ISSUE TITLE
Typeahead dropdown problem on tablets / phones

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [boneskull/angular-tags#41]
Not sure how to deal with this or if it's really an issue with angular-tags at all but I have difficulty using this component with an Android phone or tablet because the keyboard obscures the typeahead list as it always appears below the input which gets covered by the onscreen keyboard.

**Comment by boneskull** [comment]
@WhatFreshHellIsThis If you can make the same thing happen in a fiddle with ui-bootstrap, it's a ui-bootstrap issue.  Please let me know.

**Comment by WhatFreshHellIsThis** [comment]
It's more an issue that the typeahead selection box should drop "up" instead of down when it's so close to the edge, but I just put a 500px padding div at the bottom and end of problem.
