### ISSUE TITLE
Restricting number of inputs

### ISSUE THREAD

**Issue by false9striker** [boneskull/angular-tags#43]
How can i restrict the user from entering more than one input/tag. I just want to take only one input. 

Appreciate any help! Thanks.

**Comment by boneskull** [comment]
It doesn't support this behavior.  I could envision it having some sort of attribute or option that you pass to limit the number of items, in the general case.  In particular, using what's essentially a multiselect widget to select only one thing seems strange, though.

If you need this behavior soon, I encourage you to submit a PR.  If someone else also has this requirement, please reopen this issue.
